# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - method: pip
      path: ./pyben
      extra_requirements:
        - docs

sphinx:
  builder: dirhtml
  configuration: pyben/docs/conf.py
