"""Type stubs for the compiled ``binary_ensemble._core`` extension.

These describe the raw PyO3 surface. End users should import the ergonomic
facades from :mod:`binary_ensemble.stream`, :mod:`binary_ensemble.bundle`,
:mod:`binary_ensemble.codec`, and :mod:`binary_ensemble.graph` instead.
"""

from pathlib import Path
from typing import Any, Iterable, Iterator, Literal

# ---------------------------------------------------------------------------
# Stream decoder / encoder (plain .ben / .xben)
# ---------------------------------------------------------------------------

class BenDecoder:
    """Iterator over assignments in a plain BEN or XBEN stream.

    Stream-only: opening this on a ``.bendl`` bundle raises and points at
    :class:`BendlDecoder`. Sample counting is lazy and cached.
    """

    def __init__(
        self, file_path: str | Path, mode: Literal["ben", "xben"] = "ben"
    ) -> None: ...
    def __iter__(self) -> Iterator[list[int]]: ...
    def __next__(self) -> list[int]: ...
    def __len__(self) -> int: ...
    def count_samples(self) -> int: ...
    def subsample_indices(self, indices: Iterable[int]) -> "BenDecoder": ...
    def subsample_range(self, start: int, end: int) -> "BenDecoder": ...
    def subsample_every(self, step: int, offset: int = 1) -> "BenDecoder": ...
    def assignment_format(self) -> Literal["ben", "xben"]: ...

class BenEncoder:
    """Encoder for plain Binary Ensemble (`.ben`) streams."""

    def __init__(
        self,
        file_path: str | Path,
        overwrite: bool = False,
        variant: Literal["standard", "mkv_chain", "twodelta"] | None = None,
    ) -> None: ...
    def write(self, assignment: list[int]) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> "BenEncoder": ...
    def __exit__(self, exc_type, exc, tb) -> bool: ...

# ---------------------------------------------------------------------------
# Bundle decoder / encoder (.bendl)
# ---------------------------------------------------------------------------

class BendlDecoder:
    """Reader and iterator for a ``.bendl`` bundle.

    Bundle-only: opening this on a plain ``.ben``/``.xben`` stream raises and
    points at :class:`BenDecoder`. Iteration walks the embedded assignment
    stream; the bundle directory and asset payloads are exposed through the
    inspection methods. A finalized assets-only bundle (empty stream) iterates to
    nothing with ``len == 0``.
    """

    def __init__(self, file_path: str | Path) -> None: ...
    def __iter__(self) -> Iterator[list[int]]: ...
    def __next__(self) -> list[int]: ...
    def __len__(self) -> int: ...
    def count_samples(self) -> int: ...
    def subsample_indices(self, indices: Iterable[int]) -> "BendlDecoder": ...
    def subsample_range(self, start: int, end: int) -> "BendlDecoder": ...
    def subsample_every(self, step: int, offset: int = 1) -> "BendlDecoder": ...
    def assignment_format(self) -> Literal["ben", "xben"]: ...
    def version(self) -> tuple[int, int]: ...
    def is_complete(self) -> bool: ...
    def asset_names(self) -> list[str]: ...
    def list_assets(self) -> list[dict[str, Any]]: ...
    def read_asset_bytes(self, name: str) -> bytes: ...
    def read_json_asset(self, name: str) -> Any: ...
    # Returns a NetworkX graph (``networkx.Graph``/``MultiGraph``) rebuilt from the
    # stored adjacency JSON, or ``None`` if absent. Use ``read_json_asset("graph.json")``
    # for the raw parsed dict.
    def read_graph(self) -> Any | None: ...
    def read_metadata(self) -> Any | None: ...
    def read_node_permutation_map(self) -> Any | None: ...
    def extract_stream(
        self,
        out_path: str | Path,
        overwrite: bool = False,
        allow_unfinalized: bool = False,
    ) -> None: ...

class BendlStreamSession:
    """Single-use context manager over a bundle's assignment stream.

    Obtained from :meth:`BendlEncoder.stream`; finalizes the bundle on a clean
    close and leaves it unfinalized if the context exits via an exception.
    """

    def write(self, assignment: list[int]) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> "BendlStreamSession": ...
    def __exit__(self, exc_type, exc, tb) -> bool: ...

class BendlEncoder:
    """Writer for a ``.bendl`` bundle (create mode) or appender (append mode)."""

    def __init__(self, file_path: str | Path, overwrite: bool = False) -> None: ...
    @staticmethod
    def append(file_path: str | Path) -> "BendlEncoder": ...
    def add_asset(
        self, name: str, payload: bytes, content_type: Literal["json", "text"]
    ) -> None: ...
    def add_metadata(self, metadata: Any) -> None: ...
    # Returns the (possibly reordered) graph as a NetworkX graph, matching
    # BendlDecoder.read_graph.
    def add_graph(self, graph: Any, preprocess_method: str | None) -> Any: ...
    def stream(
        self,
        format: Literal["ben"] = "ben",
        variant: Literal["standard", "mkv_chain", "twodelta"] | None = None,
    ) -> BendlStreamSession: ...
    def close(self) -> None: ...
    def __enter__(self) -> "BendlEncoder": ...
    def __exit__(self, exc_type, exc, tb) -> bool: ...

# ---------------------------------------------------------------------------
# Whole-file stream / JSONL transforms
# ---------------------------------------------------------------------------

def encode_jsonl_to_ben(
    in_file: str | Path,
    out_file: str | Path,
    overwrite: bool = False,
    variant: Literal["standard", "mkv_chain", "twodelta"] = "mkv_chain",
) -> None: ...
def encode_jsonl_to_xben(
    in_file: str | Path,
    out_file: str | Path,
    overwrite: bool = False,
    variant: Literal["standard", "mkv_chain", "twodelta"] = "mkv_chain",
    n_threads: int | None = None,
    compression_level: int | None = None,
    xz_block_size: int | None = None,
) -> None: ...
def encode_ben_to_xben(
    in_file: str | Path,
    out_file: str | Path,
    overwrite: bool = False,
    n_threads: int | None = None,
    compression_level: int | None = None,
    xz_block_size: int | None = None,
) -> None: ...
def decode_ben_to_jsonl(
    in_file: str | Path, out_file: str | Path, overwrite: bool = False
) -> None: ...
def decode_xben_to_jsonl(
    in_file: str | Path, out_file: str | Path, overwrite: bool = False
) -> None: ...
def decode_xben_to_ben(
    in_file: str | Path, out_file: str | Path, overwrite: bool = False
) -> None: ...

# ---------------------------------------------------------------------------
# Graph reordering and bundle recompression
# ---------------------------------------------------------------------------

def graph_reorder(graph: Any, method: str) -> tuple[Any, Any]: ...
def recompress_bundle(
    in_file: str | Path, out_file: str | Path, overwrite: bool = False
) -> None: ...
